version: '3'
services:
  app:
    container_name: react-app-container
    image: node:14-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true